---
- name: Read boot node ENR for hosts
  command:
    cmd: "cat {{ lighthouse_enr_file }}"
  register: enr

- name: Ensure the local nodes list doesn't contain an empty array
  delegate_to: 127.0.0.1
  lineinfile:
    path: "{{ lighthouse_testnet_enr_file }}"
    line: "[]"
    state: absent

- name: Ensure the host ENR is included in local boot_nodes.yml
  delegate_to: 127.0.0.1
  lineinfile:
    path: "{{ lighthouse_testnet_enr_file }}"
    line: "- {{ enr.stdout }}"
    state: present
