---
- name: Install OS packages
  become: yes
  package:
    name:
      - git
      - cmake
      - clang
      - openssl-devel
    state: latest
- name: Update sigp/lighthouse repo
  git:
    repo: "{{ lighthouse_repo_url }}"
    dest: "{{ lighthouse_repo_dir }}"
    version: "{{ lighthouse_repo_branch }}"
- name: Cargo install lighthouse
  shell: '{{ cargo_bin_dir }}/cargo install --path lighthouse --force'
  args:
    chdir: "{{ lighthouse_repo_dir }}"
