---
- name: Ensure Lighthouse datadir exists
  file:
    path: "{{ lighthouse_dir }}"
    state: directory

- name: Use lcli to generate testnet dir
  command:
    crates: "{{ lighthouse_testnet_dir }}"
    cmd:
      argv:
        - "{{ lcli_bin }}"
        - "new-testnet"
        - "--testnet-dir"
        - "{{ lighthouse_testnet_dir }}"
        - "--min-genesis-time"
        - "{{ min_genesis_time }}"
        - "--min-genesis-delay"
        - "{{ min_genesis_delay }}"
        - "--min-deposit-amount"
        - "{{ 1000000000 / deposit_adjustment_factor }}"
        - "--max-effective-balance"
        - "{{ 16000000000 / deposit_adjustment_factor }}"
        - "--eth1-follow-distance"
        - "{{ eth1_follow_distance }}"
        - "--genesis-fork-version"
        - "{{ eth1_follow_distance }}"
        - "--deposit-contract-address"
        - "{{ deposit_contract_address }}"
        - "--deposit-contract-deploy-block"
        - "{{ deposit_contract_deploy_block }}"
