testnet_tag: unity-alpha

#
# Testnet specs
#

# Address is _without_ 0x prefix.
deposit_contract_address: "0a73d5478a04a819a3444eaa8d62d88a37a0e491"
deposit_contract_deploy_block: 2565791 
eth1_follow_distance: 16
min_genesis_time: 0
min_genesis_delay: 3600
genesis_fork_version: "0x00000000"
min_genesis_active_validator_count: 16384
min_deposit_amount: 100000000
max_effective_balance: 3200000000
effective_balance_increment: 100000000

#
# AWS EC2 config
#

# The regions in which we will deploy lighthouse nodes.
#
# Each region will effectively be a replica.
public_node_regions: ["ap-southeast-1", "eu-central-1", "us-west-2", "ap-south-1"]

# Security group names
security_group_nodes: "{{ testnet_tag}}-nodes"
security_group_metrics: "{{ testnet_tag}}-metrics"

# Beacon nodes only run a `lighthouse bn`.
beacon_node_per_region: 0
beacon_node_instance_type: t2.medium
beacon_node_volume_size_gb: 32

# Boots nodes only run a `lighthouse bn`, but their ENR are collected and
# distributed with the testnet.
boot_node_per_region: 2
boot_node_instance_type: t2.medium
boot_node_volume_size_gb: 32

# Validator nodes run `lighthouse bn` and `lighthouse vc`.
validator_per_region: 2
validator_instance_type: t2.medium
validator_volume_size_gb: 32

# Metrics (Grafana + Prometheus)
metrics_server_region: ap-southeast-1
metrics_instance_type: t2.small
metrics_volume_size_gb: 32

#
# Validator config
#

validators_per_host: 2048
validator_deposit_gwei: "{{ max_effective_balance }}"
# Give some extra ETH for gas.
eth_allowance_per_validator: 3.3
eth_per_host: "{{ validators_per_host * eth_allowance_per_validator }}"

#
# Lightouse source
#
lighthouse_repo_branch: "testnet-corrections"

#
# Lightouse debugging
#
# We will `export RUST_BACKTRACE` with this value
rust_backtrace: full
