---
- name: Destroys all infrastructure for a testnet
  hosts: localhost
  gather_facts: False
  roles:
    - aws
  vars_files:
    - ./secret.yml
  vars_prompt:
    - name: Confirm destroy
      prompt: "Are you sure you wish to DESTROY THE TESTNET? Enter to continue or Ctrl+C to abort"
      private: no
  tasks:
    - name: Terminate public node instances
      include_tasks: roles/aws/tasks/ec2-terminate.yml
      vars:
        regions: "{{ public_node_regions }}"

    - name: Terminate metrics instance
      include_tasks: roles/aws/tasks/ec2-terminate.yml
      vars:
        regions:
          - "{{ metrics_server_region }}"

    - name: Delete nodes security group
      loop: "{{ public_node_regions }}"
      ec2_group:
        region: "{{ item }}"
        name: "{{ security_group_nodes }}"
        state: absent

    - name: Delete metrics server security group
      ec2_group:
        region: "{{ metrics_server_region }}"
        name: "{{ security_group_metrics }}"
        state: absent

    - name: Get metrics server domain info
      route53:
          state: get
          zone: "{{ metrics_domain_zone }}"
          record: "{{ metrics_domain_record }}"
          type: A
      register: domain
    
    - name: Remove Route53 A-record for metrics server
      route53:
          state: absent
          zone: "{{ metrics_domain_zone }}"
          record: "{{ domain.set.record }}"
          ttl: "{{ domain.set.ttl }}"
          type: "{{ domain.set.type }}"
          value: "{{ domain.set.value }}"
