---
- name: Deploy Geth systemd unit files
  hosts: geth
  tasks:
    - name: Deploy geth.service template
      become: yes
      template:
        src: templates/geth.service.j2
        dest: /etc/systemd/system/geth.service
        force: yes
