---
- name: Destroys all EC2 instances for a given testnet
  hosts: localhost
  gather_facts: False
  roles:
    - aws
  vars_files:
    - ./secret.yml
  tasks:
    - name: Terminate Instances
      include_tasks: roles/aws/tasks/ec2-terminate.yml
