---
- name: Deploy systemd and rsyslog files
  hosts: all
  tasks:
    - name: Deploy lighthouse-bn.service template
      become: yes
      template:
        src: templates/lighthouse-bn.service.j2
        dest: /etc/systemd/system/lighthouse-bn.service
        force: yes

