---
- name: Migrates a docker-compose node over to a compiled setup
  hosts: docker
  tasks:
    - name: Create lighthouse_backup_dir
      file:
        path: "{{ lighthouse_backup_dir }}"
        state: directory
    - name: Backup network dir
      become: yes
      shell: 'cp -r {{ docker_compose_dir }}/network {{ lighthouse_backup_dir }}'
    - name: Backup validators dir
      become: yes
      when: "'validators' in group_names"
      shell: 'cp -r {{ docker_compose_dir }}/.lighthouse/validators {{ lighthouse_backup_dir }}'
    - name: chown -R lighthouse_backup_dir
      become: yes
      file:
        path: "{{ lighthouse_backup_dir }}"
        owner: "{{ ansible_user }}"
    - name: Create ~/.lighthouse
      file:
        path: "{{ lighthouse_dir }}"
        state: directory
    - name: chown -R lighthouse_dir
      become: yes
      file:
        path: "{{ lighthouse_dir }}"
        owner: "{{ ansible_user }}"
    - name: Copy backup files to .lighthouse
      shell: 'cp -r {{ lighthouse_backup_dir }}/* {{ lighthouse_dir }}'
    - name: Create ~/.lighthouse
      file:
        path: "{{ lighthouse_dir }}"
        state: directory
    - name: Stop docker-compose environment
      command: docker-compose stop
      args:
        chdir: "{{ docker_compose_dir }}"

- name: Install Geth
  import_playbook: geth-build-from-source.yml

- name: Configure systemd for Geth
  import_playbook: geth-configure-systemd.yml

- name: Start Geth
  import_playbook: geth-start.yml

- name: Install Rust
  import_playbook: rust-update.yml

- name: Build Lighthouse
  import_playbook: lighthouse-build-from-source.yml

- name: Configure systemd for Lighthouse
  import_playbook: lighthouse-configure-systemd.yml

- name: Start Beacon Node
  import_playbook: lighthouse-bn-start.yml

- name: Start Validator Client
  import_playbook: lighthouse-vc-start.yml
