---
- name: Migrates a docker-compose node over to a compiled setup
  hosts: docker
  roles:
    - common
    - geth
    - rust
    - lighthouse
  vars:
    - docker_compose_dir: "{{ home_dir }}/lighthouse-docker"
  tasks:
    - name: Create lighthouse_backup_dir
      file:
        path: "{{ lighthouse_backup_dir }}"
        state: directory
    - name: Backup network dir
      become: yes
      shell: 'cp -r {{ docker_compose_dir }}/network {{ lighthouse_backup_dir }}'
    - name: Backup validators dir
      become: yes
      when: "'validators' in group_names"
      shell: 'cp -r {{ docker_compose_dir }}/.lighthouse/validators {{ lighthouse_backup_dir }}'
    - name: chown -R lighthouse_backup_dir
      become: yes
      file:
        path: "{{ lighthouse_backup_dir }}"
        recurse: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
    - name: Create ~/.lighthouse
      file:
        path: "{{ lighthouse_dir }}"
        state: directory
    - name: chown -R lighthouse_dir
      become: yes
      file:
        path: "{{ lighthouse_dir }}"
        recurse: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
    - name: Copy backup files to .lighthouse
      shell: 'cp -r {{ lighthouse_backup_dir }}/* {{ lighthouse_dir }}'
    - name: Create ~/.lighthouse
      file:
        path: "{{ lighthouse_dir }}"
        state: directory
    - name: Stop docker-compose environment
      command: docker-compose stop
      args:
        chdir: "{{ docker_compose_dir }}"
    - name: Build Geth from source
      include_tasks: roles/geth/tasks/build-from-source.yml
    - name: Configure systemd for Geth
      include_tasks: roles/geth/tasks/configure-systemd.yml
    - name: Start Geth systemd service
      include_tasks: roles/geth/tasks/start.yml
    - name: Install Rust
      include_tasks: roles/rust/tasks/install.yml
    - name: Build Lighthouse from source
      include_tasks: roles/lighthouse/tasks/build-from-source.yml
    - name: Configure systemd for Lighthouse
      include_tasks: roles/lighthouse/tasks/configure-systemd.yml
    - name: Start Beacon Node
      include_tasks: roles/lighthouse/tasks/bn-start.yml
    - name: Start Validator Client
      include_tasks: roles/lighthouse/tasks/vc-start.yml
