---
- name: Destroys all infrastructure for a testnet and refunds deposit contract
  hosts: localhost
  gather_facts: False
  roles:
    - aws
    - lighthouse
    - common
    - geth
  vars_files:
    - ./secret.yml
  vars_prompt:
    - name: Confirm destroy
      prompt: "Are you sure you wish to DESTROY THE TESTNET? Enter to continue or Ctrl+C to abort"
      private: no
  tasks:
    - name: Terminate public node instances
      include_tasks: roles/aws/tasks/ec2-terminate.yml
      vars:
        regions: "{{ public_node_regions }}"

    - name: Terminate metrics instance
      include_tasks: roles/aws/tasks/ec2-terminate.yml
      vars:
        regions:
          - "{{ metrics_server_region }}"

    - name: Remove security groups
      include_tasks: roles/aws/tasks/ec2-security-groups-destroy.yml

    - name: Get metrics server domain info
      route53:
          state: get
          zone: "{{ metrics_domain_zone }}"
          record: "{{ metrics_domain_record }}"
          type: A
      register: domain
    
    - name: Remove Route53 A-record for metrics server
      when: domain.set
      route53:
          state: absent
          zone: "{{ metrics_domain_zone }}"
          record: "{{ domain.set.record }}"
          ttl: "{{ domain.set.ttl }}"
          type: "{{ domain.set.type }}"
          value: "{{ domain.set.value }}"

    - name: Refund deposit contract
      command: 
        cmd: "{{ cargo_bin_dir }}/lcli refund-deposit-contract --eth1-ipc {{ geth_ipc_endpoint }} --from-address {{ local_eth_address }} --contract-address {{ deposit_contract_address }}"
