---
- name: Destroys all EC2 instances for a given testnet
  hosts: localhost
  gather_facts: False
  roles:
    - aws
  vars_files:
    - roles/aws/vars/secret.yml
  vars:
    - aws_regions: ["ap-southeast-1"]
    - testnet_tag: "paultesting"
  tasks:
    - name: Terminate Instances
      include_tasks: roles/aws/tasks/ec2-terminate.yml
