- name: Create lighthouse-ansible keypair
  loop: "{{ aws_regions }}"
  ec2_key:
    name: "{{ aws_key_name }}"
    region: "{{ item }}"
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    key_material: "{{ ec2_pubkey }}"
    force: no
- name: Launch AWS instances
  loop: "{{ aws_regions }}"
  ec2:
     key_name: "{{ aws_key_name }}"
     aws_access_key: "{{ ec2_access_key }}"
     aws_secret_key: "{{ ec2_secret_key }}"
     instance_type: t2.micro
     image: "{{ aws_ami_id }}"
     region: "{{ item }}"
     wait: true
     exact_count: "{{ instances_per_aws_region }}"
     count_tag:
        testnet: "{{ testnet_tag }}"
     instance_tags:
        Owner: "{{ aws_owner }}"
        testnet: "{{ testnet_tag }}"
  register: ec2
