- name: Gather instance info
  loop: "{{ aws_regions }}"
  ec2_instance_info:
    region: "{{ item }}"
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    filters:
      "tag:Owner": "{{ aws_owner }}"
      "tag:Testnet": "{{ testnet_tag }}"
  register: instances
- name: Terminate AWS instances
  loop: "{{ aws_regions }}"
  ec2:
     aws_access_key: "{{ ec2_access_key }}"
     aws_secret_key: "{{ ec2_secret_key }}"
     region: "{{ item }}"
     instance_ids: "{{ instances['results'][0]['instances'] | map(attribute='instance_id') | list }}"
     state: absent

