---
- name: Ensure lighthouse-ansible keypair exists
  loop: "{{ regions }}"
  ec2_key:
    name: "{{ aws_key_name }}"
    region: "{{ item }}"
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    key_material: "{{ ec2_pubkey }}"
    force: no

- name: Launch AWS instances
  loop: "{{ regions }}"
  ec2:
     key_name: "{{ aws_key_name }}"
     aws_access_key: "{{ ec2_access_key }}"
     aws_secret_key: "{{ ec2_secret_key }}"
     instance_type: "{{ instance_type }}"
     image: "{{ aws_ami_id }}"
     region: "{{ item }}"
     group: "{{ testnet_tag }}"
     wait: true
     exact_count: "{{ instance_count }}"
     volumes:
      - device_name: /dev/xvda
        volume_type: gp2
        volume_size: "{{ volume_gb }}"
     count_tag:
        Testnet: "{{ testnet_tag }}"
        CountId: "{{ count_id_tag }}"
     instance_tags: "{{ tags }}"
  register: ec2
