---
- name: yum install go
  become: yes
  yum:
    name: go
    state: latest

- name: Update geth repo
  git:
    repo: "{{ geth_repo_url }}"
    dest: "{{ geth_repo_dir }}"
    version: "{{ geth_repo_version }}"

- name: Build geth
  command: make geth
  args:
    chdir: "{{ geth_repo_dir }}"

- name: Symlink /build/bin/geth to /usr/bin
  become: yes
  file:
    src: "{{ geth_repo_dir }}/build/bin/geth"
    dest: /usr/bin/geth
    state: link

