---
- name: Get address of first Geth keystore
  script: "../scripts/geth_wallet_address.py {{ geth_keystore_dir }}"
  register: wallet

- name: Deploy geth.service template
  become: yes
  template:
    src: ../templates/geth.service.j2
    dest: /etc/systemd/system/geth.service
    force: yes
