---
- name: Provisions ETH to nodes
  hosts:
    - lighthouse_vc
  roles:
    - common
    - geth
  tasks:
    - name: Provide initial eth1 wallet and ETH
      include_tasks: roles/geth/tasks/create-and-endow-wallet.yml
