testnet_tag: exampletestnet

#
# Testnet specs
#

# Address is _without_ 0x prefix.
deposit_contract_address: "fcfbb059c845eaead96b7b5531ab7157de9a9da1"
deposit_contract_deploy_block: 2532176 
eth1_follow_distance: 16
min_genesis_time: 0
min_genesis_delay: 3600
genesis_fork_version: "0x00000000"
min_genesis_active_validator_count: 1024
min_deposit_amount: "{{ 100000000 }}"
max_effective_balance: "{{ 3200000000 }}"

aws_regions: ["ap-southeast-1"]
beacon_node_per_region: 1
boot_node_per_region: 1
validator_per_region: 1
validators_per_host: 1
gwei_validator_deposit: "{{ max_effective_balance }}"
eth_allowance_per_validator: 3.2005
eth_per_host: "{{ validators_per_host * eth_allowance_per_validator }}"

