---
- name: Destroys all EC2 instances for a given testnet
  hosts: localhost
  gather_facts: False
  roles:
    - aws
  vars_files:
    - ./secret.yml
  vars_prompt:
    - name: Confirm destroy
      prompt: "Are you sure you wish to destroy the testnet?"
      private: no
  tasks:
    - name: Terminate Public Node Instances
      include_tasks: roles/aws/tasks/ec2-terminate.yml
      vars:
        regions: "{{ public_node_regions }}"
    - name: Terminate Metrics Instance
      include_tasks: roles/aws/tasks/ec2-terminate.yml
      vars:
        regions:
          - "{{ metrics_server_region }}"
